<h1 style = "background-color: #80a5d6; font-family:Quicksand; font-weight: 500; color:white;line-height: 3em; padding-left: 1em; "> KH√ÅM PH√Å V√Ä TI·ªÄN X·ª¨ L√ù D·ªÆ LI·ªÜU </h1>

<h2> üìÇ IMPORT TH∆Ø VI·ªÜN C·∫¶N THI·∫æT </h2>

In [1]:
import pandas as pd

---

<h2> üìÇ KH√ÅM PH√Å D·ªÆ LI·ªÜU </h2>

### üõí 1. ƒê·ªçc d·ªØ li·ªáu t·ª´ file excel v√†o dataframe

Ta ch·ªâ quan t√¢m ƒë·∫øn 2 sheet ƒë·∫ßu ti√™n l√† `Orders` v√† `Returns`

In [20]:
# Orders sheet
df_order = pd.read_excel("../datasets/global_superstore_2016.xlsx", sheet_name = "Orders")
df_order.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,1,MX-2015-SC2057582-42279,2015-10-02,2015-10-06,Standard Class,SC-2057582,Sonia Cooley,Consumer,NaN,Mexico City,...,OFF-LA-4658,Office Supplies,Labels,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,2.033,Medium
1,2,MX-2013-KW1657028-41562,2013-10-15,2013-10-20,Standard Class,KW-1657028,Kelly Williams,Consumer,NaN,Dos Quebradas,...,FUR-FU-6238,Furniture,Furnishings,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.449,Medium
2,3,MX-2013-KW1657028-41562,2013-10-15,2013-10-20,Standard Class,KW-1657028,Kelly Williams,Consumer,NaN,Dos Quebradas,...,FUR-BO-4845,Furniture,Bookcases,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.627,Medium
3,4,MX-2013-KW1657028-41562,2013-10-15,2013-10-20,Standard Class,KW-1657028,Kelly Williams,Consumer,NaN,Dos Quebradas,...,OFF-BI-3720,Office Supplies,Binders,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.371,Medium
4,5,MX-2013-KW1657028-41562,2013-10-15,2013-10-20,Standard Class,KW-1657028,Kelly Williams,Consumer,NaN,Dos Quebradas,...,OFF-AR-5905,Office Supplies,Art,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.787,Medium

In [21]:
# Returns sheet
df_return = pd.read_excel("../datasets/global_superstore_2016.xlsx", sheet_name = "Returns")
df_return.head(5)

  Returned                  Order ID        Region
0      Yes  CA-2012-SA20830140-41210    Central US
1      Yes  IN-2012-PB19210127-41259  Eastern Asia
2      Yes  CA-2012-SC20095140-41174    Central US
3      Yes    IN-2015-JH158207-42140       Oceania
4      Yes    IN-2014-LC168857-41747       Oceania

### üõí 2. D·ªØ li·ªáu g·ªìm bao nhi√™u d√≤ng v√† bao nhi√™u c·ªôt?

In [22]:
num_rows_order, num_cols_order = df_order.shape
num_rows_return, num_cols_return = df_return.shape

print('Orders sheet:', num_rows_order, 'd√≤ng v√†', num_cols_order, 'c·ªôt.')
print('Returns sheet:', num_rows_return, 'd√≤ng v√†', num_cols_return, 'c·ªôt.')

Orders sheet: 51290 d√≤ng v√† 24 c·ªôt.
Returns sheet: 1079 d√≤ng v√† 3 c·ªôt.

### üõí 3. M·ªói d√≤ng c√≥ √Ω nghƒ©a g√¨? C√≥ v·∫•n ƒë·ªÅ c√°c d√≤ng c√≥ √Ω nghƒ©a kh√°c nhau kh√¥ng?

Theo quan s√°t s∆° b·ªô v·ªÅ t·∫≠p d·ªØ li·ªáu:

- V·ªõi `Orders` sheet: m·ªói d√≤ng cho bi·∫øt c√°c th√¥ng tin li√™n quan ƒë·∫øn m·ªôt giao d·ªãch ·ªü c·ª≠a h√†ng. 

- V·ªõi `Returns` sheet: m·ªói d√≤ng cho bi·∫øt m√£ ƒë∆°n h√†ng v√† khu v·ª±c n∆°i ƒë∆°n h√†ng b·ªã ho√†n tr·∫£ cho Superstore. 

Trong c·∫£ 2 sheet, c√≥ v·∫ª kh√¥ng c√≥ d√≤ng n√†o kh√¥ng ph√π h·ª£p.

### üõí 4. D·ªØ li·ªáu c√≥ c√°c d√≤ng b·ªã l·∫∑p kh√¥ng?

In [23]:
def check_duplicated(data):
    check = data.duplicated().sum()
    if check == 0:
        print('D·ªØ li·ªáu kh√¥ng b·ªã l·∫∑p!')
    else:
        print('C√≥ d√≤ng b·ªã l·∫∑p, ki·ªÉm tra l·∫°i!')

check_duplicated(df_order)
check_duplicated(df_return)

D·ªØ li·ªáu kh√¥ng b·ªã l·∫∑p!
D·ªØ li·ªáu kh√¥ng b·ªã l·∫∑p!

### üõí 5. M·ªói c·ªôt c√≥ √Ω nghƒ©a g√¨?

Xem trong ph·∫ßn **B. Kh√°m ph√° d·ªØ li·ªáu** file `data_collection.ipynb`.

---

<h2> üìÇ TI·ªÄN X·ª¨ L√ù D·ªÆ LI·ªÜU </h2>

### üõí 6. B·ªè ƒëi c·ªôt `Postal Code` v√¨ thi·∫øu d·ªØ li·ªáu qu√° nhi·ªÅu

In [24]:
# T·ª∑ l·ªá d·ªØ li·ªáu thi·∫øu c·ªßa c·ªôt `Postal Code`
missing_ratio_postal = df_order['Postal Code'].isna().sum() / len(df_order['Postal Code']) * 100
print(f'Missing ratio of "Postal Code": {round(missing_ratio_postal, 2)}%')

Missing ratio of "Postal Code": 80.51%

In [25]:
# Ngo√†i vi·ªác thi·∫øu d·ªØ li·ªáu qu√° nhi·ªÅu, ta c≈©ng kh√¥ng c√≥ nhu c·∫ßu s·ª≠ d·ª•ng m√£ b∆∞u ch√≠nh c·ªßa c√°c th√†nh ph·ªë n√™n ta quy·∫øt ƒë·ªãnh b·ªè c·ªôt `Postal Code`
df_order.drop(columns = "Postal Code", axis = 1, inplace = True)
num_cols_order = df_order.shape[1]
print('S·ªë c·ªôt c·ªßa d·ªØ li·ªáu: ', num_cols_order)

S·ªë c·ªôt c·ªßa d·ªØ li·ªáu:  23

### üõí 7. Kh√°m ph√° c√°c d√≤ng d·ªØ li·ªáu v·ªÅ Vi·ªát Nam

In [26]:
df_order[df_order["Country"] == "Vietnam"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
20327,20328,IN-2014-AM10705144-41849,2014-07-29,2014-08-04,Standard Class,AM-10705144,Anne McFarland,Consumer,Ho Chi Minh City,Ho Ch√≠ Minh City,...,OFF-LA-5376,Office Supplies,Labels,"Novimex Color Coded Labels, Alphabetical",20.3184,2,0.17,0.2184,1.83,Medium
20328,20329,IN-2014-AM10705144-41849,2014-07-29,2014-08-04,Standard Class,AM-10705144,Anne McFarland,Consumer,Ho Chi Minh City,Ho Ch√≠ Minh City,...,TEC-AC-5122,Technology,Accessories,"Logitech Memory Card, Erganomic",268.1535,5,0.47,-207.4965,13.79,Medium
20329,20330,IN-2014-AM10705144-41849,2014-07-29,2014-08-04,Standard Class,AM-10705144,Anne McFarland,Consumer,Ho Chi Minh City,Ho Ch√≠ Minh City,...,TEC-AC-5204,Technology,Accessories,"Memorex Memory Card, Erganomic",318.2544,6,0.47,-114.1056,10.74,Medium
20330,20331,IN-2014-AM10705144-41849,2014-07-29,2014-08-04,Standard Class,AM-10705144,Anne McFarland,Consumer,Ho Chi Minh City,Ho Ch√≠ Minh City,...,TEC-CO-3611,Technology,Copiers,"Brother Wireless Fax, Laser",238.6503,1,0.37,22.7103,14.54,Medium
20501,20502,IN-2015-DK12985144-42346,2015-12-08,2015-12-13,Standard Class,DK-12985144,Darren Koutras,Consumer,Hanoi,Th·ªß D√¥ H√† N·ªôi,...,OFF-ST-6057,Office Supplies,Storage,"Smead Shelving, Blue",162.4476,4,0.17,52.7676,17.37,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30271,30272,IN-2015-MP18175144-42328,2015-11-20,2015-11-23,First Class,MP-18175144,Mike Pelletier,Home Office,Ho Chi Minh City,Ho Ch√≠ Minh City,...,OFF-BI-4812,Office Supplies,Binders,"Ibico Binder, Durable",70.4670,5,0.17,3.2670,5.64,Medium
30272,30273,IN-2015-MP18175144-42328,2015-11-20,2015-11-23,First Class,MP-18175144,Mike Pelletier,Home Office,Ho Chi Minh City,Ho Ch√≠ Minh City,...,OFF-AP-4961,Office Supplies,Appliances,"KitchenAid Refrigerator, Red",2190.9510,5,0.17,316.7010,280.47,Medium
30273,30274,IN-2015-MP18175144-42328,2015-11-20,2015-11-23,First Class,MP-18175144,Mike Pelletier,Home Office,Ho Chi Minh City,Ho Ch√≠ Minh City,...,FUR-FU-3027,Furniture,Furnishings,"Advantus Door Stop, Black",65.7438,2,0.27,12.5838,1.60,Medium
30274,30275,IN-2015-MP18175144-42328,2015-11-20,2015-11-23,First Class,MP-18175144,Mike Pelletier,Home Office,Ho Chi Minh City,Ho Ch√≠ Minh City,...,FUR-FU-5737,Furniture,Furnishings,"Rubbermaid Photo Frame, Durable",35.6094,1,0.27,9.7494,6.10,Medium
30275,30276,IN-2015-MP18175144-42328,2015-11-20,2015-11-23,First Class,MP-18175144,Mike Pelletier,Home Office,Ho Chi Minh City,Ho Ch√≠ Minh City,...,FUR-BO-4859,Furniture,Bookcases,"Ikea Floating Shelf Set, Traditional",643.8852,6,0.37,-337.2948,93.00,Medium

#### üîé Ta th·∫•y c√≥ ƒë√¥i ch·ªó sai ch√≠nh t·∫£ (khi c√≥ d·∫•u khi kh√¥ng c√≥ d·∫•u) trong t√™n th√†nh ph·ªë (City) v√† t·ªânh th√†nh (State) c·ªßa Vi·ªát Nam. Ta c·∫ßn ƒëi·ªÅu ch·ªânh l·∫°i cho th·ªëng nh·∫•t

In [27]:
def convert_city(city_name):
    if city_name == "Ho Chi Minh City":
        return "TP.HCM"
    elif city_name == "Hanoi":
        return "H√† N·ªôi"
    elif city_name == "Da Nang":
        return "ƒê√† N·∫µng"
    elif city_name == "Can Tho":
        return "C·∫ßn Th∆°"
    elif city_name == "Rach Gia":
        return "R·∫°ch Gi√°"
    else:
        return city_name
    
def convert_state(state_name):
    if state_name == "Ho Ch√≠ Minh City":
        return "TP.HCM"
    elif state_name == "Th·ªß D√¥ H√† N·ªôi":
        return "H√† N·ªôi"
    elif state_name == "D√† Nang":
        return "ƒê√† N·∫µng"
    elif state_name == "T·ªânh C·∫ßn Th∆°":
        return "C·∫ßn Th∆°"
    else:
        return state_name
    
df_order["City"] = df_order["City"].apply(convert_city)
df_order["State"] = df_order["State"].apply(convert_state)

### üõí 8. M·ªói c·ªôt hi·ªán ƒëang c√≥ ki·ªÉu d·ªØ li·ªáu g√¨? C√≥ c·ªôt n√†o c√≥ ki·ªÉu d·ªØ li·ªáu ch∆∞a ph√π h·ª£p ƒë·ªÉ c√≥ th·ªÉ x·ª≠ l√Ω ti·∫øp kh√¥ng?

In [30]:
col_dtypes_order = pd.Series(df_order.dtypes)
col_dtypes_order

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

In [31]:
col_dtypes_return = pd.Series(df_return.dtypes)
col_dtypes_return

Returned    object
Order ID    object
Region      object
dtype: object

#### üîé T√¨m hi·ªÉu v·ªÅ c√°c c·ªôt c√≥ ki·ªÉu object trong `Orders` sheet

In [32]:
def object_dtype(s):
    dtypes = set()
    s.apply(lambda x : dtypes.add(type(x)))
    return dtypes

In [33]:
list_object_order = list(col_dtypes_order.loc[col_dtypes_order.values == object].index)
list_type_order = []

for i in list_object_order:
    list_type_order.insert(len(list_type_order), object_dtype(df_order[i]))
    
type_object_order = pd.Series(list_type_order, list_object_order)
print(type_object_order)

Order ID          {<class 'str'>}
Ship Mode         {<class 'str'>}
Customer ID       {<class 'str'>}
Customer Name     {<class 'str'>}
Segment           {<class 'str'>}
City              {<class 'str'>}
State             {<class 'str'>}
Country           {<class 'str'>}
Region            {<class 'str'>}
Market            {<class 'str'>}
Product ID        {<class 'str'>}
Category          {<class 'str'>}
Sub-Category      {<class 'str'>}
Product Name      {<class 'str'>}
Order Priority    {<class 'str'>}
dtype: object

#### üîé T√¨m hi·ªÉu v·ªÅ c√°c c·ªôt c√≥ ki·ªÉu object trong `Returns` sheet

In [34]:
list_object_return = list(col_dtypes_return.loc[col_dtypes_return.values == object].index)
list_type_return = []

for i in list_object_return:
    list_type_return.insert(len(list_type_return), object_dtype(df_return[i]))
    
type_object_return = pd.Series(list_type_return, list_object_return)
print(type_object_return)

Returned    {<class 'str'>}
Order ID    {<class 'str'>}
Region      {<class 'str'>}
dtype: object

##### üí° **Ta th·∫•y r·∫±ng**: n√™n ƒë∆∞a t·∫•t c·∫£ c√°c c·ªôt tr√™n v·ªÅ `string` ƒë·ªÉ ti·∫øp t·ª•c kh√°m ph√° th√™m c√°c c·ªôt n√†y.

In [35]:
for col in list_object_order:
    df_order[col] = df_order[col].astype('string')
for col in list_object_return:
    df_return[col] = df_return[col].astype('string')

---

<h2> üìÇ QUAY L·∫†I B∆Ø·ªöC KH√ÅM PH√Å D·ªÆ LI·ªÜU </h2>

Trong ph·∫ßn n√†y ta t√¨m hi·ªÉu s·ª± ph√¢n b·ªë c√°c gi√° tr·ªã ·ªü c√°c c·ªôt `categorical` v√† `numeric` c·ªßa `Orders` sheet

### üõí 9. V·ªõi m·ªói c·ªôt c√≥ ki·ªÉu d·ªØ li·ªáu d·∫°ng categorical, ta t√¨m hi·ªÉu s·ª± ph√¢n b·ªë c√°c gi√° tr·ªã

üîé C√°c c·ªôt trong `list_object_order` thu·ªôc nh√≥m `Categorical`.

V·ªõi m·ªói c·ªôt `categorical`, ta th·ª±c hi·ªán t√≠nh % gi√° tr·ªã thi·∫øu (t·ª´ 0 - 100), s·ªë l∆∞·ª£ng gi√° tr·ªã kh√°c nhau (kh√¥ng x√©t gi√° tr·ªã thi·∫øu), list/array c√°c gi√° tr·ªã kh√°c nhau (kh√¥ng x√©t gi√° tr·ªã thi·∫øu) v√† l∆∞u k·∫øt qu·∫£ v√†o `cate_col_df`. Dataframe n√†y c√≥ 3 c·ªôt l√† `"missing_ratio", "num_diff_vals", "diff_vals"`; v√† c√≥ c√°c d√≤ng l√† c√°c c·ªôt d·ªØ li·ªáu thu·ªôc nh√≥m categorical.

In [37]:
col_cate_info = ["missing_ratio", "num_diff_vals", "diff_vals"]
cate_col_df = pd.DataFrame(columns = col_cate_info, index = list_object_order)

def cate_values(col):
    missing_ratios = df_order[col].isna().sum() / len(df_order) * 100
    num_diff = df_order[col].dropna().nunique()
    diff_value = list(df_order[col].dropna().unique())

    return missing_ratios, num_diff, diff_value

for col in list_object_order:
    cate_col_df.loc[col] = cate_values(col)

cate_col_df

,missing_ratio,num_diff_vals,diff_vals
Order ID,0.0,25728,"[MX-2015-SC2057582-42279, MX-2013-KW1657028-41..."
Ship Mode,0.0,4,"[Standard Class, Second Class, First Class, Sa..."
Customer ID,0.0,17415,"[SC-2057582, KW-1657028, DP-1300018, TB-212509..."
Customer Name,0.0,796,"[Sonia Cooley, Kelly Williams, Darren Powers, ..."
Segment,0.0,3,"[Consumer, Home Office, Corporate]"
City,0.0,3650,"[Mexico City, Dos Quebradas, S√£o Paulo, Managu..."
State,0.0,1102,"[Distrito Federal, Risaralda, S√£o Paulo, Manag..."
Country,0.0,165,"[Mexico, Colombia, Brazil, Nicaragua, Panama, ..."
Region,0.0,23,"[Central America, South America, Caribbean, No..."
Market,0.0,5,"[LATAM, Europe, Asia Pacific, USCA, Africa]"
Product ID,0.0,3788,"[OFF-LA-4658, FUR-FU-6238, FUR-BO-4845, OFF-BI..."
Category,0.0,3,"[Office Supplies, Furniture, Technology]"
Sub-Category,0.0,17,"[Labels, Furnishings, Bookcases, Binders, Art,..."
Product Name,0.0,3788,"[Hon File Folder Labels, Adjustable, Tenex Clo..."
Order Priority,0.0,4,"[Medium, Low, High, Critical]"

### üõí 10. V·ªõi m·ªói c·ªôt c√≥ ki·ªÉu d·ªØ li·ªáu d·∫°ng numeric, ta t√¨m hi·ªÉu s·ª± ph√¢n b·ªë c√°c gi√° tr·ªã

üîé Ta x√©t c√°c c·ªôt `Sales, Quantity, Profit, Shipping Cost` thu·ªôc nh√≥m `Numeric`.

V·ªõi m·ªói c·ªôt `numeric`, ta s·∫Ω t√≠nh t·ªâ l·ªá % gi√° tr·ªã thi·∫øu (t·ª´ 0 ƒë·∫øn 100), min, max. Sau ƒë√≥ l∆∞u k·∫øt qu·∫£ v√†o dataframe `nume_col_profiles_df`. Dataframe n√†y c√≥ 6 c·ªôt l√† `"missing_ratio", "min", "lower_quartile", "median", "upper_quartile", "max"` v√† c√≥ c√°c d√≤ng l√† c√°c c·ªôt d·ªØ li·ªáu thu·ªôc nh√≥m numeric.

In [38]:
col_numeric = ["Sales", "Quantity", "Profit", "Shipping Cost"]
col_num_info = ["missing_ratio", "min", "lower_quartile", "median", "upper_quartile", "max"]
num_col_df = pd.DataFrame(columns = col_num_info, index = col_numeric)

def num_values(col):
    missing_ratios = (df_order[col].isna().sum() / len(df_order) * 100)
    min_value = df_order[col].min()
    median = df_order[col].median()
    lower_quartile = df_order[col].quantile(q = 0.25, interpolation = 'lower')
    upper_quartile = df_order[col].quantile(q = 0.75, interpolation = 'higher')
    max_value = df_order[col].max()

    return missing_ratios, min_value, lower_quartile, median, upper_quartile, max_value

for col in col_numeric:
    num_col_df.loc[col] = num_values(col)

num_col_df

,missing_ratio,min,lower_quartile,median,upper_quartile,max
Sales,0.0,0.444,30.756,85.053,251.0676,22638.48
Quantity,0.0,1,2,3.0,5,14
Profit,0.0,-6599.978,0.0,9.24,36.81,8399.976
Shipping Cost,0.0,1.002,2.61,7.79,24.45,933.57

### üõí 11. Sau khi kh√°m ph√° v√† ti·ªÅn x·ª≠ l√Ω d·ªØ li·ªáu xong, ta s·∫Ω xu·∫•t ra m·ªôt file excel kh√°c ƒë·ªÉ ph·ª•c v·ª• cho c√°c b∆∞·ªõc ti·∫øp theo

In [40]:
with pd.ExcelWriter('../datasets/global_superstore_clean.xlsx') as writer:
    df_order.to_excel(writer, sheet_name = 'Orders', index = False)
    df_return.to_excel(writer, sheet_name = 'Returns', index = False)